name: second workflow
on:
  workflow_dispatch:

env:
  WORKFLOW_VAR: "THis is workflow variable"

jobs:
  firstJob:
    runs-on: ubuntu-latest
    name: this is the first job
    steps:
      - uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4.0.0
        with: 
          path: ~/.npm
          key: buildCache
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: upload code coverage
        uses: actions/upload-artifact@v4.3.1
        with:
          name: codecoverage
          path: coverage
      - name: build
        run: npm run build
      - name: upload build files
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build
          path: build
          
