name: second workflow
on:
  workflow_dispatch:

env:
  WORKFLOW_VAR: "THis is workflow variable"

jobs:
  firstJob:
    runs-on: ubuntu-latest
    name: this is the first job
    env:
      JOB_VAR: "This is job variable"
    steps:
      - name: firstJob script
        shell: bash
        run: echo hello there!! this is the 1st job!
      - name: checkout
        uses: actions/checkout@v4
      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ github.actor }}
      - name: time
        run: |
          echo "The time of the greeting was at: ${{ steps.print-to-log.outputs.time }}"

  secondJob:
    runs-on: ubuntu-latest
    steps:
      - name: secondJob script
        shell: bash
        run: |
          echo this is the second jbo
          echo and this is a multi line script
      - name: environment variable
        env:
          STEP_VAR: "THis is a step variable"
          
